# LIST: they are ordered and unchangeable. duplicate is okay.
fruits_lst = ["apple", "banana", "coconut", "orange"]
print(f"LIST: {fruits_lst}")
print(fruits_lst[0])
print(fruits_lst[1])
print(fruits_lst[2])
print(fruits_lst[3])
print(fruits_lst[0:1])
print(fruits_lst[::-1])
print(fruits_lst[::])
print(len(fruits_lst))
print("pineapple" in fruits_lst)
fruits_lst[0]= "pineapple"
print(fruits_lst)
fruits_lst.append("apple")
print(fruits_lst)
fruits_lst.remove("pineapple")
print(fruits_lst)
fruits_lst.insert(2, "melon")
print(fruits_lst)
fruits_lst.sort()
print(fruits_lst)
fruits_lst.reverse()
print(fruits_lst)
print(fruits_lst.index("apple"))
print(fruits_lst.count("banana"))
fruits_lst.clear()
print(fruits_lst)
#fruits_lst.pop()
# print(fruits_lst)

# SET:unordered and immutable, but able to add/ remove. no duplicates
fruits_set = {"apple", "banana", "coconut", "orange"}
print(f"SET: \n{fruits_set}")
#print(dir(fruits_set))
#rint(help(fruits_set))
print(len(fruits_set))
print("pineapple" in fruits_set)
fruits_set.add("pineapple")
print(fruits_set)
fruits_set.remove("banana")
print(fruits_set)
fruits_set.pop()
print(fruits_set)

#TUPLES: ordered and unchangeable. able to duplicate. faster
fruits_tpl = ("apple", "banana", "coconut", "orange", "coconut")
print(f"TUPLE: \n{fruits_tpl}")
# print(dir(fruits_tpl))
# print(help(fruits_tpl))
print(fruits_tpl[1])
print(len(fruits_tpl))
print("pineapple" in fruits_tpl)
print(fruits_tpl.index("apple"))
print(fruits_tpl.count("banana"))
for fruit in fruits_tpl:
    print(fruit)

fruit_set = list()